README.md
This set of steps describes how a new release is made.
This protocol ensures that backwards-breaking changes are not released with a "major-compatible" version number, causing projects that depend on this library to break unexpectedly.
It also ensures better ability to track what changes were made. This helps the discovery of regressions and gives a better overview of each release.
---
Note that I've applied this protocol for the releases 0.1.5 and 0.2.0. They appear here:
- https://github.com/Neptune-Crypto/twenty-first/tags
- https://crates.io/crates/twenty-first/versions
Note also that the releases 0.1.0, 0.1.1, 0.1.2 and 0.1.3 don't (yet) have git tags.
=> README: Add release protocol

twenty-first/src/util_types/mmr/archival_mmr.rs, twenty-first/src/util_types/mmr/mmr_accumulator.rs, twenty-first/src/util_types/mmr/mmr_membership_proof.rs, twenty-first/src/util_types/mmr/mmr_trait.rs
I need this for manipulating MMR membership proofs through nested calls
=> Change signature of MMR function to mutate membership proofs

twenty-first/src/shared_math/rescue_prime_regular.rs
This results in a ~19% speedup of `RescuePrimeRegular::hash_varlen()`.
Running `cargo bench varlen` before and after:
```
Benchmarking rescue_prime_regular/hash_varlen/RescuePrimeRegular / Hash Variable Length/16384:
time before:  [28.763 ms 28.812 ms 28.866 ms]
time after:   [23.233 ms 23.252 ms 23.277 ms]
change:      [-19.462%  -19.296%  -19.133%] (p = 0.00 < 0.05)
```
=> Drain padded input instead of re-allocating vector

twenty-first/src/shared_math/mpolynomial.rs
This allows us to put the multivariate polynomials into HashSet which will
be required for an efficient implementation of circuits. Through this HashSet
we can check if we are inserting a value that has already been encountered
and if so then use that already encountered value instead.
=> Allow hashing of multivariate polynomials

twenty-first/src/shared_math/traits.rs, twenty-first/src/shared_math/x_field_element.rs, twenty-first/src/util_types/proof_stream_typed.rs
- `pub const EXTENSION_DEGREE: usize = 3;`
- Add the following instances:
- `impl Add<XFieldElement> for XFieldElement` (original)
- `impl Add<BFieldElement> for XFieldElement` (new)
- `impl Add<XFieldElement> for BFieldElement` (new)
- `impl Mul<XFieldElement> for XFieldElement` (original)
- `impl Mul<BFieldElement> for XFieldElement` (new)
- `impl Mul<XFieldElement> for BFieldElement` (new)
- `impl Sub<XFieldElement> for XFieldElement` (original)
- `impl Sub<BFieldElement> for XFieldElement` (new)
- `impl Sub<XFieldElement> for BFieldElement` (new)
Assert that they corresponding to lifting the BFieldElements.
**Note:** This only warrants a minor bump.
=> Arithmetic overloading

stark-brainfuck/Cargo.toml, stark-brainfuck/src/stark.rs, stark-brainfuck/src/xfri.rs, stark-rescue-prime/Cargo.toml, stark-rescue-prime/src/stark_rp.rs, twenty-first/src/shared_math/fri.rs, twenty-first/src/util_types.rs, twenty-first/src/util_types/merkle_tree.rs, twenty-first/src/util_types/merkle_tree_maker.rs, twenty-first/src/util_types/mmr/archival_mmr.rs
A `MerkleTree<M, T>` is parameterised over both
- `H: AlgebraicHasher`
- `M: MerkleTreeMaker`
so that both the hash function and the method of assembling the Merkle tree may vary.
This warrants a `0.x+1.0` version bump on next release.
The reviewer may benefit from reviewing one commit at a time.
=> MerkleTreeMaker

.github/workflows/main.yml
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
> Pinning an action to a full length commit SHA is currently the only
> way to use an action as an immutable release. Pinning to a particular
> SHA helps mitigate the risk of a bad actor adding a backdoor to the
> action's repository, as they would need to generate a SHA-1 collision
> for a valid Git object payload.
=> Pin GitHub CI actions to commit digests

twenty-first/src/shared_math/b_field_element.rs, twenty-first/src/shared_math/rescue_prime_digest.rs, twenty-first/src/shared_math/traits.rs, twenty-first/src/shared_math/x_field_element.rs, twenty-first/src/util_types/algebraic_hasher.rs
Various small changes
- Add Digest::emojihash(&self)
- Remove 'impl Default for XFieldElement'
- Remove BFieldElement::from_byte_array() 
- Hashable: Test that .to_sequence() returns expectable lengths
- Remove impl From<Digest> for [u8; MSG_DIGEST_SIZE_IN_BYTES]
=> Hashable objects

twenty-first/Cargo.toml, twenty-first/src/shared_math/b_field_element.rs
This leads to a 20-30 % reduction in time for NTT on my P17 machine and a 15-25 % reduction in runtime with an AMD Threadripper 5995.
The internal representation of the B field element is a bit more complicated now, so some of the tests had to be changed as well as they shouldn't access or have opinions about the internal representation, only the results of various calculations.
=> Switch to Montgomery representation on B field

twenty-first/src/util_types/mmr/archival_mmr.rs, twenty-first/src/util_types/mmr/mmr_accumulator.rs, twenty-first/src/util_types/mmr/mmr_membership_proof.rs, twenty-first/src/util_types/mmr/shared.rs
- Introduce new method, `right_lineage_length` to calculate what was previously referred to as *right ancestor count*.
- Introduce test showing that it agrees with and is faster than the method it displaces.
- Exercise naming rights: rename function `right_ancestor_count_and_own_height` to `right_lineage_length_and_own_height`.
- Refactor: use method that computes only the lineage length wherever the own height is not needed.
=> Right Lineage Length

twenty-first/src/shared_math/b_field_element.rs
Since the Montgomery representation of a B field element is unique, we can rely on the derived `Hash` and `PartialEq` implementations. We don't need custom implementations anymore.
=> Remove custom `Hash` and `PartialEq` implementations

twenty-first/src/amount/u32s.rs
- `impl<const N: usize> Distribution<U32s<N>> for Standard`
- U32s tests: Split `get_u32s()` use into `random_elements()` and `random_masked_u32s()`
The motivation is to make [tasm-lib](https://github.com/TritonVM/tasm-lib) tests for `u64` operators more readable.
The main part of this commit is:
```rust
impl<const N: usize> Distribution<U32s<N>> for Standard {
fn sample<R: Rng + ?Sized>(&self, rng: &mut R) -> U32s<N> {
let values = rng.sample::<[u32; N], Standard>(Standard);
U32s { values }
}
}
```
This enables:
```rust
// Generate a single random value
let mut rng = rand::thread_rng();
let single: U32s<N> = rng.gen();
use twenty_first::shared_math::other::{random_elements, random_elements_array};
// Generate a vector of `n: usize` random values
let many_vec: Vec<U32s<N>> = …
```
=> Generate random `U32s<N>`s

twenty-first/src/shared_math/b_field_element.rs, twenty-first/src/shared_math/tip5.rs
Inline a few functions used in tip5 to gain a 1-3 % speedup on the tip5 benchmark.
No inling
tip5/hash_10/Tip5 / Hash 10/10
time:   [747.29 ns 752.33 ns 758.48 ns]
tip5/hash_varlen/Tip5 / Hash Variable Length/16384
time:   [2.5593 ms 2.5771 ms 2.6001 ms]
tip5/parallel/Tip5 / Parallel Hash/65536
time:   [1.4635 ms 1.4834 ms 1.5058 ms]
With inlining
tip5/hash_10/Tip5 / Hash 10/10
time:   [722.53 ns 727.50 ns 733.53 ns]
tip5/hash_varlen/Tip5 / Hash Variable Length/16384
time:   [2.5468 ms 2.5718 ms 2.5997 ms]
tip5/parallel/Tip5 / Parallel Hash/65536
time:   [1.4324 ms 1.4548 ms 1.4830 ms]
=> Inline tip5-related functions for a small speedup

stark-rescue-prime/benches/stark_rp.rs, stark-rescue-prime/src/lib.rs, stark-rescue-prime/src/stark_rp.rs, twenty-first/Cargo.toml, twenty-first/benches/rescue_prime_regular.rs, twenty-first/benches/sponge_hashing.rs, twenty-first/benches/tip5.rs, twenty-first/src/shared_math/b_field_element.rs, twenty-first/src/shared_math/other.rs, twenty-first/src/shared_math/rescue_prime_digest.rs, twenty-first/src/shared_math/rescue_prime_optimized.rs, twenty-first/src/shared_math/rescue_prime_regular.rs, twenty-first/src/util_types/algebraic_hasher.rs
In order to hash things equivalently in the Rust/tasm implementations of the STARK verifier, it is necessary to expose the same hashing primitives in both environments. For Merkle-tree hashing, this was already fixed using `RescuePrimeRegular::hash_10()` in both `AlgebraicHasher::hash_pair()` and in Triton VM's `hash` instruction.
Other cases of hashing in the STARK verifier includes Fiat-Shamir challenges / sampling indices / sampling weights.
The proposed solution (which also affects how variable-length hashing works in general) is to expose sponge instructions (`absorb_init`, `absorb`, `squeeze`) in the VM (TritonVM/triton-vm#166, TritonVM/triton-vm#168), for which the primitives are ported back to a trait in twenty-first, `SpongeHasher`.
A `hash_varlen()` is also made with …
=> SpongeHasher

twenty-first/Cargo.toml, twenty-first/benches/tip5.rs, twenty-first/src/shared_math/tip5.rs, twenty-first/src/util_types/algebraic_hasher.rs
- Remove Tip5::hash_varlen() in favor of AlgebraicHasherNew::hash_varlen().
- Since Tip5::permutation() takes a &self that contains a precomputed table and precomputed round constants, create a globally accessible immutable singleton reference to avoid recomputing these on every call to hash_*().
=> impl SpongeHasher + AlgebraicHasher + AlgebraicHasherNew for Tip5

twenty-first/benches/poseidon.rs, twenty-first/benches/poseidon_naive.rs, twenty-first/benches/rescue_prime_optimized.rs, twenty-first/benches/rescue_prime_regular.rs, twenty-first/benches/tip5.rs, twenty-first/src/shared_math/lattice.rs, twenty-first/src/shared_math/mpolynomial.rs, twenty-first/src/shared_math/tip5.rs, twenty-first/src/test_shared/mmr.rs, twenty-first/src/util_types.rs, twenty-first/src/util_types/mmr/archival_mmr.rs, twenty-first/src/util_types/storage_schema.rs, twenty-first/src/util_types/storage_vec.rs
The file `storage_schema.rs` introduces a bunch of structs and traits (and implementations!) that abstract out the database-specific logic of containers-with-persistence. This allows the user to write logic relative to standard rust containers (such as `Vec`) and then switch to a container-with-persistance (such as `DbtVec`, defined in this PR) which has the same interface but also provides an interface for the host application to restore from or persist to database.
=> Abstract Storage Schema

twenty-first/src/shared_math/x_field_element.rs, twenty-first/src/util_types/merkle_tree.rs
This allows more efficient Merkle tree building if the leaves don't need prior compression.
=> add canonical interpretation of XFieldElements as Digests

twenty-first/Cargo.toml, twenty-first/benches/merkle_tree_authenticate.rs, twenty-first/src/util_types/merkle_tree.rs
This PR brings multiple goodies.
- A benchmark for verifying partial Merkle authentication paths.
- A tremendous speedup when verifying partial authentication paths: what used to take ~500ms now takes ~650μs. Yes, you've read that right, the new code for verifying the particular de-duplicated Merkle tree authentication structure from the new benchmark shaves off ~99.87%[^2] of the runtime. This is achieved by performing as little hashing as possible.[^1]
- The expected height of the Merkle tree for the which the authentication structure is claimed to be valid is now an obligatory parameter. If any partial authentication path does not conform to this expected height, validation will fail.
- A bug fix in the logic of generating partial authentication paths.
- Big code readability …
=> improve on Merkle tree's de-duplicated authentication structure generation & verification

bfieldcodec_derive/src/lib.rs, twenty-first/Cargo.toml, twenty-first/src/lib.rs, twenty-first/src/shared_math/bfield_codec.rs, twenty-first/src/shared_math/tip5.rs, twenty-first/src/util_types/merkle_tree.rs, twenty-first/src/util_types/mmr/mmr_accumulator.rs
- Use the new macro in more places.
- Add documentation, including example and known limitations.
- Allow ignoring fields via attribute `#[bfield_codec(ignore)]`. Ignored fields must implement `Default`.
- Make usage of the macro more stable through fully qualified names.
- Slight code cleanup.
=> make `BFieldCodec` derive macro more stable and feature complete

bfieldcodec_derive/src/lib.rs, twenty-first/Cargo.toml, twenty-first/src/shared_math/b_field_element.rs, twenty-first/src/shared_math/bfield_codec.rs, twenty-first/src/shared_math/digest.rs, twenty-first/src/shared_math/x_field_element.rs, twenty-first/src/util_types/mmr/mmr_accumulator.rs
This PR updates the derive macro for BFieldCodec so that the generated code is aware when the size of encoded objects is statically known. As a result, objects with statically-known encoding sizes are not length-prepended.
Also this PR adds support for deriving BFieldCodec for enums.
=> Awareness of Static Sizes in BFieldCodec

twenty-first/src/shared_math/ntt.rs
The new test in this PR depends on the implementation of the `Arbitrary` trait for `BFieldElement` that is introduced in #142. The bug fix does not.
=> fix edge case bugs in (i)NTT

twenty-first/benches/tip5.rs, twenty-first/src/shared_math/digest.rs, twenty-first/src/shared_math/tip5.rs, twenty-first/src/shared_math/x_field_element.rs, twenty-first/src/test_shared.rs, twenty-first/src/util_types/algebraic_hasher.rs, twenty-first/src/util_types/blake3_wrapper.rs, twenty-first/src/util_types/merkle_tree.rs, twenty-first/src/util_types/mmr/archival_mmr.rs, twenty-first/src/util_types/mmr/mmr_accumulator.rs, twenty-first/src/util_types/mmr/mmr_membership_proof.rs, twenty-first/src/util_types/mmr/mmr_trait.rs, twenty-first/src/util_types/mmr/shared_basic.rs, twenty-first/src/util_types/shared.rs
Most of the changes in this PR are boring deletion or addition of `&`s. The following things might be of interest:
- changes to the interface `hash_pair` in `AlgebraicHasher`
- commit 05a0da6b4758e11cc839dc80eb3356655663467e, introducing a benchmark
- commit e38a966acd24aa3b2b94e1620e0df94adca20da9, avoiding some copying
=> avoid borrowing copy-type `Digest`

twenty-first/src/util_types/storage_schema.rs, twenty-first/src/util_types/storage_vec.rs
This removes the overhead of grabbing and releasing locks. AFAIK it does *not* decrease the number of times that we read from disk since the underlying leveldb-database does not have batch-getters.
This code ended up being more complicated than I wanted it to. But it's fairly well tested, so I think we're good.
=> Add batch-getters for DB wrappers

twenty-first/src/util_types/storage_schema.rs, twenty-first/src/util_types/storage_vec.rs
close #155.
Adds set methods and makes locking less granular.
storage_vec.rs:
* add set_many, set_all to StorageVec trait and implementors
* add set_all_by_array default trait method to StorageVec
* add tests for set_many, set_all
* set op optimization: remove matching overwrite ops from disk write_queue
* add doc comments for StorageVec trait methods
storage_schema.rs:
* add trait WithLock
* add WithLock::len_with_lock() and ::write_op_overwrite_with_lock()
* refactor existing fn to acquire self.lock only once each.
* refactor set_* ops to each call ::write_op_overwrite_with_lock()
* set op optimization: remove prev overwrite ops from disk write_queue
* make ::pull_queue() a bit more concise
* add tests for set_many, set_all
=> feat: add set_many(), set_all() to storage vecs

twenty-first/src/storage/storage_vec/iterators.rs
This method is needed by neptune-core.    It was just an oversight it was not originally included.
=> fix: add StorageSetter::index() method

twenty-first/Cargo.toml, twenty-first/benches/merkle_tree.rs, twenty-first/benches/merkle_tree_auth_structure_size.rs, twenty-first/benches/merkle_tree_authenticate.rs, twenty-first/src/shared_math/digest.rs, twenty-first/src/test_shared.rs, twenty-first/src/util_types/merkle_tree.rs, twenty-first/src/util_types/merkle_tree_maker.rs, twenty-first/src/util_types/mmr/archival_mmr.rs
=> improve `MerkleTree` implementation

twenty-first/src/storage/storage_schema/dbtsingleton.rs, twenty-first/src/storage/storage_schema/dbtvec.rs, twenty-first/src/storage/storage_schema/schema.rs, twenty-first/src/storage/storage_schema/simple_rusty_storage.rs, twenty-first/src/storage/storage_vec/iterators.rs, twenty-first/src/storage/storage_vec/ordinary_vec.rs, twenty-first/src/storage/storage_vec/rusty_leveldb_vec.rs, twenty-first/src/storage/storage_vec/traits.rs, twenty-first/src/sync/atomic_mutex.rs, twenty-first/src/sync/atomic_rw.rs, twenty-first/src/sync/mod.rs, twenty-first/src/sync/shared.rs
This PR consists of two commits that:
1) Adds an optional lock name and event callback fn to `AtomicRw` and `AtomicMutex`, which enables applications to log/trace all lock events  (TryAcquire, Acquire, Release).
2) makes use of the event callback functionality within the `Storage` types, again in a way that is optional for the application.
**Breaking Changes:**
There is one breaking API change that I'm aware of.   I added a field to `DbtSchema` which previously could only be created by direct struct {..} instantiation.   So there is no way to add a field in a non-breaking way.   This pr also adds DbtSchema::new(). 
**Motivation:**
I wanted to be able to log/trace all lock events in neptune-core, to be able to track which threads and tokio tasks are using each lock and in what manner. …
=> Lock notifications pr

twenty-first/src/storage/level_db.rs
fixes #175
make `storage::level_db::tests::level_db_close_and_reload` pass on windows.
<strike>we create a temp db in order to drop the existing DB, which is preventing deletion of the underlying file.</strike>
We make `DB::db` an `Option` which allows gaining ownership of the `leveldb::Database` inside `impl Drop`.  We can then drop the `Database`, which closes the underlying file and allows deletion.
<strike>This is a draft PR until I verify tests pass  on windows.</strike>
Tests are passing on all 3 platforms.
=> fix: remove DB file on Drop, for windows.

bfieldcodec_derive/src/lib.rs
Updates the BFieldCodec macro to be friendly to crates that use twenty-first via re-export.
previously:
`  ::twenty-first::<path>`
now:
`  crate::twenty-first::path`
So a dependent crate needs to do this in lib.rs:
`  use twenty_first;`
or if using twenty-first via re-export in `dep_crate`:
`  use dep_crate::twenty_first;`
See writeup at:
https://github.com/TritonVM/tasm-lib/pull/68
-----
**Testing:** I was able to build tasm-lib without any dependency on twenty-first.   Previously it would give build errors.  So, working as intended.
```
$ cargo tree --no-dedupe -f "{lib}" | grep "triton\|twenty\|neptune\|tasm_lib\|bfield"
tasm_lib
└── triton_vm
├── twenty_first
│   ├── bfieldcodec_derive
```
=> build: prefix macro use statements with crate::

twenty-first/src/storage/storage_schema/dbtsingleton.rs, twenty-first/src/storage/storage_schema/dbtsingleton_private.rs, twenty-first/src/storage/storage_schema/mod.rs, twenty-first/src/storage/storage_schema/schema.rs
By adding a deterministically derived value from the schema, the number of tables added to the schema, and using this as a key for the underlying leveldb database, we can ensure that no key collissions happen, as all tables have a unique prefix that *all* their keys start with.
This closes #177.
=> Fix potential db-key collission for singleton and dbtvec length

twenty-first/src/shared_math/tip5.rs, twenty-first/src/util_types/algebraic_hasher.rs, twenty-first/src/util_types/blake3_wrapper.rs
Also renames two `SpongeHasher` trait functions.
This closes #183.
=> Allow repeated sponge-absorption without mutating a list

twenty-first/src/prelude.rs, twenty-first/src/shared_math/tip5.rs, twenty-first/src/util_types/algebraic_hasher.rs, twenty-first/src/util_types/blake3_wrapper.rs
This is an implementation of the suggestion made [in this comment](https://github.com/Neptune-Crypto/twenty-first/pull/184#issuecomment-1914312403) on #184. Concretely, I propose to use `fn foo(&mut self, …)` in favor of `fn foo(the_thing: &mut TheThing, …)` wherever possible. This allows to write, for example, `self.squeeze()` as opposed to `Self::squeeze(&mut sponge_state)`.
Additionally, I propose to merge the unit struct `Tip5` with the state struct `Tip5State` under the rationale that they are very tightly coupled and we gain no benefit from pulling the two apart.[^blake]
Of note and probably of particular interest to @aszepieniec: I was unable to detect any performance change in `Tip5` across the 3 benchmarks I ran.
Other, minor points:
- rename `SpongeHasher` to `Sponge`
- improve …
=> simplify `SpongeHasher` trait

twenty-first/src/prelude.rs, twenty-first/src/shared_math/b_field_element.rs, twenty-first/src/shared_math/x_field_element.rs
The main addition are the `bfe!` and `xfe!` macros.  They simplify construction of `BFieldElements` and `XFieldElements`, respectively.
Additionally,
- `BFieldElement::from` can now deal with `u8`, `u16`, and `i32`.
- `XFieldElement::from` can now deal with `T` and `[T; EXTENSION_DEGREE]` where `T` is any type that can be converted into a `BFieldElement`.
=> simplify field element construction

twenty-first/src/math/bfield_codec.rs
This implementation prevents and disallows trailing zeros in the coefficients list when the polynomial is encoded. This is done to ensure that the encoding of a polynomial is unique, and that proof streams containing polynomials become as simple and short as possible.
Motivated by:
<https://github.com/TritonVM/triton-vm/issues/268>
This closes #200.
=> feat: Implement `BFieldCodec` for `Polynomial`

twenty-first/src/error.rs, twenty-first/src/math/b_field_element.rs, twenty-first/src/math/digest.rs
Addresses #195.
Any attempt to instantiate a Digest from bytes or a string with embedded non-canonical u64 values now results in an error.
Note that it is still possible to instantiate a Digest from BFieldElements that were created from non-canonical u64. Maybe that's ok...?
Changes:
* adds TryFromDigestError::NotCanonical
* adds BFieldElement::is_canonical()
* Digest::from_str() returns NotCanonical error
* Digest::try_from(bytes) returns NotCanonical error
* adds Digest test try_from_bytes_not_canonical()
* adds Digest test from_str_not_canonical()
* adds Canonical test in digest_from_invalid_hex_errors()
--------
Commentary:
I am not entirely happy with this solution/pr for two reasons:
1. it only partially addresses the issue. It remains possible to bypass the canonical checks by …
=> fix: Digest::try_from() returns NotCanonical error

twenty-first/Cargo.toml, twenty-first/benches/evaluation.rs, twenty-first/benches/formal_power_series_inverse.rs, twenty-first/benches/interpolation.rs, twenty-first/benches/poly_mod_reduce.rs, twenty-first/src/math/ntt.rs, twenty-first/src/math/polynomial.rs, twenty-first/src/util_types/mmr/mmr_accumulator.rs
This PR
- Use clever math to accelerate modular reduction of one polynomial by another, especially when the modulus has much lower degree.
- Test the introduced methods.
- Integrate the fast modular reduction into the batch evaluation dispatcher pipeline, resulting in faster batch evaluation.
- Separate the parallel from sequential code paths.
=> Fast Reduce

twenty-first/src/math/polynomial.rs
This PR fixes `fast_reduce`.
Function `fast_reduce` did not work when the modulus had structure, in particular when it had trailing zeros. The issue was that `structured_multiple` lost track of trailing zeros in the course of reversing coefficient vectors.
=> Fix Fast Reduce

twenty-first/src/amount/u32s.rs, twenty-first/src/math/b_field_element.rs, twenty-first/src/math/bfield_codec.rs, twenty-first/src/math/digest.rs, twenty-first/src/math/lattice.rs, twenty-first/src/math/ntt.rs, twenty-first/src/math/polynomial.rs, twenty-first/src/math/tip5.rs, twenty-first/src/math/traits.rs, twenty-first/src/math/x_field_element.rs, twenty-first/src/math/zerofier_tree.rs, twenty-first/src/util_types/algebraic_hasher.rs, twenty-first/src/util_types/mmr/mmr_accumulator.rs
Allow writing the following code:
```rust
fn old_and_bland<FF: FiniteField>() {            fn new_and_shiny<FF: FiniteField>() {
let many_ones = [FF::one(); 42];                 let many_ones = [FF::ONE; 42];
/* important stuff */                            /* important stuff */
}                                                }
```
Hopefully, this allows the compiler to optimize more. For example, there might be a performance difference between the following two snippets.
```rust
// current                                       // new – maybe faster?
let mut my_vec = vec![0; 0];                     let mut my_vec = vec![0; 0];
my_vec.resize(1024, FF::zero());                 my_vec.resize(1024, FF::ZERO);
```
Whether this is actually true remains to be seen.
- Replace `BFIELD_ZERO` and …
=> Use `num_traits::Const{Zero, One}`

twenty-first/benches/tip5.rs, twenty-first/src/error.rs, twenty-first/src/math/digest.rs, twenty-first/src/math/tip5.rs, twenty-first/src/util_types/algebraic_hasher.rs
Also, deprecate `digest::DIGEST_LENGTH`.
I think this design is cleaner. It's a bit of a bikeshed. :shrug: Open to suggestions.
=> refactor: Make `Digest::LEN` an associated const

twenty-first/src/error.rs, twenty-first/src/math/b_field_element.rs, twenty-first/src/math/digest.rs, twenty-first/src/util_types/mmr/mmr_accumulator.rs
- Reject non-canonical `BFieldElement`s when parsing string slices or interpreting byte sequences
- Move canon check of `BFieldElement`s from `Digest` to `BFieldElement`
- Deprecate functionality for platform-dependent endianness when decoding
BREAKING CHANGE: The error variant `NotCanonical` from enum `TryFromDigestError` has moved into enum `ParseBFieldElementError`.
This was described as the cleaner solution in #199, a sentiment I concur with.
Supersedes #206.
=> Move canon check from `Digest` to `BFieldElement`

twenty-first/benches/formal_power_series_inverse.rs, twenty-first/src/math/bfield_codec.rs, twenty-first/src/math/polynomial.rs, twenty-first/src/math/x_field_element.rs, twenty-first/src/math/zerofier_tree.rs
Refactor polynomials to (a) make their innards private and (b) turn their innards into a clone-on-write slice, reducing the number of allocations needed for read-only operations like polynomial evaluation.
- Certain functions, like evaluation, can happen without owning the coefficients, which reduces memory consumption.
- There are fewer sneaky memory allocations, _i.e._, it is more obvious in calling code whether allocations are happening. [^exceptions]
- Explicit lifetimes are required more often.
- Polynomial's implementations of traits `Zero` and `One` are less usable now. Should `poly.is_zero()` be unusable due to lifetime constraints (“`poly` escapes the method body”), you can use `poly.degree() < 0` instead.
A lot of lines have changed only because of re-grouping to avoid multiple …
=> Optionally borrow polynomial coefficients

twenty-first/src/error.rs, twenty-first/src/util_types/mmr.rs, twenty-first/src/util_types/mmr/mmr_accumulator.rs, twenty-first/src/util_types/mmr/mmr_membership_proof.rs, twenty-first/src/util_types/mmr/mmr_successor_proof.rs, twenty-first/src/util_types/mmr/shared_basic.rs
Improve the average & worst-case time & memory performance of verifying that one MMR Accumulator is the successor of some other MMR Accumulator, and document the new algorithm.
An explanation of the verification algorithm follows. As an example, take the following Merkle Mountain Range with 42 = 101010₂ leafs. Peaks are marked with `·`s.
```
·
╭───────────────┴───────────────╮
╭───────┴───────╮               ╭───────┴───────╮               ·
╭───┴───╮       ╭───┴───╮       ╭───┴───╮       ╭───┴───╮       ╭───┴───╮
╭─┴─╮   ╭─┴─╮   ╭─┴─╮   ╭─┴─╮   ╭─┴─╮   ╭─┴─╮   ╭─┴─╮   ╭─┴─╮   ╭─┴─╮   ╭─┴─╮   ·
╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮ ╭┴╮
```
Adding 8 leafs to it results in the following new Merkle Mountain Range with 50 = 110010₂ leafs. The addition …
=> perf(MmrSuccessorProof): Use shorter auth paths

twenty-first/src/math/tip5.rs
=> feat : Implement Hasher trait for Tip5

twenty-first/benches/tip5.rs, twenty-first/src/math/tip5.rs
The last step of `hash_varlen` is to read out the hash from the state. Previous this reading-out was followed by a permutation. But since the of the sponge is dropped after the termination of this function, the last permutation is not needed.
For short inputs to `hash_varlen` this gives a significant speedup. Short instances of `hash_varlen` is used downstream by `neptune-core` in the pow-guessing process, where this change reduces the number of permutations from nine to seven.
Added benchmark shows a 28 % speedup when running `hash_varlen` on an input of length 10. For longer input lengths, this speedup will approach zero.
Shoutout to @macro-ss for identifying this speedup.
Benchmark results, with this change:
```bash
$ cargo criterion --bench tip5
Compiling twenty-first v0.48.0 …
```
=> perf(tip5): Avoid one permutation in `hash_varlen`

.github/workflows/versions.yml
Add a new workflow which obtains
- the rust version from the project's rust-toolchain.toml
- the rust version from the CI toolchain
and tests that they are equal.
=> ci: Check equality of rust versions

.github/workflows/main.yml, .github/workflows/versions.yml, rust-toolchain.toml
Possibly due to https://github.com/rust-lang/rustup/issues/4337, our CI runners did not install all required components anymore and failed. By specifying the version to use explicitly when installing the toolchain, subsequent commands should work again.
=> ci: Specify rust version explicitly

twenty-first/src/config.rs, twenty-first/src/lib.rs, twenty-first/src/util_types/merkle_tree.rs
After having observed the performance difference between RAM-hungry and RAM-frugal root computation in #257, I got perf hungry. This PR brings some of that performance boost to RAM-hungry Merkle tree building.
The commits are self-contained and it might make sense to review them in isolation.
02720bef: Where previously, parallelization happened only within a given tree layer, now multiple subtrees are computed in parallel.
9e96e848: The underlying `nodes` vector is initialized in parallel. This is a less clear-cut performance boost, as it is a slowdown for small trees (height roughly less than 18) but a definitive win for trees larger than that. (The exact numbers depend on the concrete hardware.) This commit introduces some `unsafe` code and should be reviewed with the appropriate …
=> perf: Speed up parallel Merkle tree building
