twenty-first/Cargo.toml, twenty-first/src/shared_math/b_field_element.rs, twenty-first/src/shared_math/traits.rs, twenty-first/src/shared_math/x_field_element.rs
* Usage: `BFieldElement::new(0).to_emoji()`
* Write tests that demonstrate usage
* Clippy is happy
=> implement `.emojihash()` on `BFieldElement` and `XFieldElement`

twenty-first/src/shared_math/b_field_element.rs, twenty-first/src/shared_math/traits.rs, twenty-first/src/shared_math/x_field_element.rs
=> Add `inverse_or_zero()` to {B, X}FieldElement

stark-brainfuck/src/vm.rs, twenty-first/clippy.toml, twenty-first/src/shared_math/mpolynomial.rs, twenty-first/src/util_types/merkle_tree.rs
=> ignore zero-coefficients for computing polynomials total degree

twenty-first/src/timing_reporter.rs
Layout timer reports for easier human comparison of measurements
Fix bug:  The printing of the table header (here: 2.01μs) would
artificially lower the average and increase the std. dev.
Before a table was printed like this:
```
avg = 61.55ms, std.dev. = 52.18ms
Table name: ProgramTable with lifted matrix with data  2.01µs
initial quotients                                      53.77ms
Done calculating consistency quotients                 40.69ms
transition quotients                                   55.34ms
terminal quotients                                     157.95ms
-----------------------------------------------------  ------------
total                                                  307.75ms
```
With this patch it is instead printed like this:
```
ProgramTable with lifted matrix …
```
=> Layout timer reports for easier human comparison of measurements

twenty-first/src/shared_math/b_field_element.rs, twenty-first/src/shared_math/rescue_prime_digest.rs, twenty-first/src/shared_math/x_field_element.rs, twenty-first/src/util_types.rs, twenty-first/src/util_types/emojihash_trait.rs
- Move .emojihash() to Emojihash trait
- Create generic impls for vectors, arrays, slices
- Use generic impls for XFieldElement and Digest
=> Emojihash trait

twenty-first/Cargo.toml, twenty-first/benches/merkle_tree.rs
Signed-off-by: Einar Rasmussen <einar@neptune.cash>
=> Implement benchmark for `MerkleTree`

twenty-first/src/shared_math/b_field_element.rs, twenty-first/src/shared_math/polynomial.rs, twenty-first/src/shared_math/x_field_element.rs, twenty-first/src/util_types/mmr/shared.rs
- Add modular reduction function
- Add fixed tests
- Rename const variable `QUOTIENT` to `P`
=> Minor Improvements

twenty-first/benches/rescue_prime_optimized.rs, twenty-first/benches/rescue_prime_regular.rs, twenty-first/benches/sponge_hashing.rs, twenty-first/benches/tip5.rs, twenty-first/src/shared_math/rescue_prime_optimized.rs, twenty-first/src/shared_math/rescue_prime_regular.rs, twenty-first/src/shared_math/tip5.rs, twenty-first/src/util_types/algebraic_hasher.rs, twenty-first/src/util_types/blake3_wrapper.rs, twenty-first/src/util_types/merkle_tree.rs, twenty-first/src/util_types/proof_stream_typed.rs
- hash_slice() becomes hash_varlen()
- impl SpongeHasher + AlgebraicHasher for blake3::Hasher
=> Replace old AlgebraicHasher with AlgebraicHasher: SpongeHasher

twenty-first/Cargo.toml, twenty-first/src/shared_math.rs, twenty-first/src/shared_math/fips202.rs, twenty-first/src/shared_math/lattice.rs, twenty-first/src/shared_math/ntt.rs
A straightforward of an IND-CCA2-secure [key encapsulation mechanism](https://eprint.iacr.org/2002/174.pdf) following the IND-CPA-secure public key encryption scheme described in [1].
[1]: Alan Szepieniec and Frederik Vercauteren. Lattice-based Cryptography in Miden VM. https://eprint.iacr.org/2022/1041.pdf
=> Lattice-Based Key Encapsulation

twenty-first/src/util_types/mmr/shared_advanced.rs, twenty-first/src/util_types/mmr/shared_basic.rs
Thank you, OEIS: [A005187](https://oeis.org/A005187).
=> simplify MMR index arithmetic

twenty-first/Cargo.toml, twenty-first/benches/merkle_tree_auth_structure_size.rs, twenty-first/benches/merkle_tree_authenticate.rs, twenty-first/src/shared_math/bfield_codec.rs, twenty-first/src/util_types/merkle_tree.rs
- more compact authentication structure
- cleaner generation of authentication structure
Fix #123.
=> simpler Merkle tree authentication structure

twenty-first/benches/merkle_tree_auth_structure_size.rs, twenty-first/src/shared_math/other.rs, twenty-first/src/util_types/merkle_tree.rs, twenty-first/src/util_types/mmr/archival_mmr.rs, twenty-first/src/util_types/mmr/shared_advanced.rs
=> add method to construct Merkle authentication paths from authentication structure

twenty-first/src/shared_math/ntt.rs
We can avoid an extra branch in this code by requiring the provided log2 value to be zero for an empty array.
=> Avoid new branch in NTT

twenty-first/src/shared_math/b_field_element.rs
Refactor and clean up some BFieldElement tests so that they only do one thing. Use an actual property testing framework for property based tests.
=> use property based tests for BFieldElement

twenty-first/src/util_types/storage_schema.rs, twenty-first/src/util_types/storage_vec.rs
=> Add method to get all elements of persisted DB vectors

twenty-first/src/amount/dyadic_rationals.rs
=> Fix ordering of dyadic rationals

twenty-first/src/shared_math/polynomial.rs, twenty-first/src/shared_math/x_field_element.rs
- Fixes one broken tests
- Adds motivation for a test involving XFieldElement division / use of XGCD
- Removes unused function `XFieldElement::gdcd`; XFieldElement was already using the one in `polynomial.rs` for division.
=> Xgcd thv additions

twenty-first/src/shared_math/b_field_element.rs
Previously, (de)serialization used the internal, i.e., Montgomery representation. Now, deserializing (for example) a “1” gives the `BFieldElement` 1.
The motivation for this change comes from the [debugger for Triton VM](https://github.com/TritonVM/triton-vm/pull/242). Concretely, when specifying digests for non-deterministic input, they currently have to be specified with the components in Montgomery representation. I believe this to be confusing, as the digest appearing on the VM's stack will seemingly differ from the specified digest.
=> (de)serialize `BFieldElement` in canonical representation

twenty-first/src/storage/storage_schema/schema.rs
Addresses https://github.com/Neptune-Crypto/twenty-first/issues/163#issuecomment-1886209708
=> docs: fix restore_or_new() placement in doctests

twenty-first/benches/various_muls.rs
Fix benchmark for multiplication of various data types
=> Mul benches

twenty-first/src/math/bfield_codec.rs
This field-length value is needed in the encoding to allow downstream dependencies to treat an encoded polynomial stored in Triton VM RAM as any other struct, since all encoded struct are assumed to be encoded consistently with a derived `BFieldCodec` implementation.
This closes #203.
=> fix!: Add field-length indicator to BFE encoding of polynomial

twenty-first/src/util_types/mmr/mmr_successor_proof.rs
suggested change to `MmrSuccessorProof`.
Use Merkle tree node index instead of a length of a vector for inner-loop's stop condition. Also make `verify` more structured by reducing use of early return.
=> refactor(mmr_successor_proof): Flatten digest list

twenty-first/src/math/digest.rs
This allows formatting using the `:x` and `:X` modifiers, like `print!("{digest:x}")`.
@dan-da, would this make sense?
=> feat: Implement `{Lower, Upper}Hex` for `Digest`

twenty-first/src/math/b_field_element.rs, twenty-first/src/math/bfield_codec.rs
Implement `BFieldCodec` for `u8` and `u16`, and many type conversions to and from `BFieldElement`.
=> Support more types in `BFieldCodec` and in `BFieldElement` conversion

twenty-first/src/util_types/merkle_tree.rs
In particular, the function `authentication_structure_node_indices` can now work with many more types than just `usize`. For example, and what sparked this refactoring, type `u64` now works, but so do many other primitive types.
BREAKING CHANGE: Remove the payload from error variant `MerkleTreeError::LeafIndexInvalid`.
=> refactor(merkle_tree): Make helper method generic
